### ISSUE TITLE
Simplify color palette and re-engineer sass color variables

### ISSUE THREAD

**Issue by sethburtonhall** [ushahidi/platform-pattern-library#148]
# Summary 

The platform color palette has gotten out of control and needs to be simplified. Doing so will allow me to re-design the sass variables, which will allow for quicker client customization.

**Steps:**
- [x] rethink and simplify the PL color palette
- [x] re-design the sass variables and revise the css to reflect
- [ ] test by changing a few sass color variables to see custom colors reflected across all modules and layouts
- [x] critique from @Erioldoesdesign 

New colour palette **Pending tests in the client and PL**:

```//NEW COLOURS

//brand colours
$dark-blue: #373E46;
$gold: #FFC334;

//backgrounds
$bg-white: #FFFFFF;
$bg-grey: #F1F1F4;

//mid greys
$dark-grey: #777777;
$diabled-grey: #D0D0D0;

//Dark
$black: #1E232A;

//links
$link-blue: #0000E0;

//alerts
$success-green: #007A4B;
$error-red: #EB0202;
```

Looks like this:
<img width="966" alt="screen shot 2018-03-12 at 2 24 18 pm" src="https://user-images.githubusercontent.com/29209303/37307602-1e63663e-2601-11e8-88e1-8821d411bf8e.png">

.scss file attached with the new mapping: [new-colours.scss.zip](https://github.com/ushahidi/platform-pattern-library/files/1804435/new-colours.scss.zip)

Design rationale in comments.

**Comment by justinscherer** [comment]
# Design rationale

## Problem

Our old colour palette had **64** colours in it. Now it has **10**

They looked like this:

![labelledoldpalette](https://user-images.githubusercontent.com/29209303/37307869-da019e42-2601-11e8-820b-03b7061d409f.png)

And this:

![similar together](https://user-images.githubusercontent.com/29209303/37307874-deedf7d4-2601-11e8-825c-401b7dea24df.png)

The palette had several drawbacks:
1. Many of the colours were so similar as to be indistinguishable
2. There are too many of them which makes colour customizations difficult for client projects
3. The vast majority of colour combinations are were not accessible 
4. The frequent use of `lighten()` and `darken()` functions in Sass makes the colours very difficult to understand
5. Aesthetically, there were a lot of muddy mid-to-light greys
6. Links have the same colour as normal text, and as a result are not accessible because they are indistinguishable from normal text. 

## Process
I started by mapping out the current palette and grouping similar colours together (see above). 

I took one good colour from each cluster, and grouped them semantically according to their function in the UI. 
![culled](https://user-images.githubusercontent.com/29209303/37308278-25b6555c-2603-11e8-91dc-ac0cd9296f7f.png)

Then I tweaked the blue for links and red and green for alerts to colours that are accessible (i.e. 4.5:1) on a white background. I also added one more mid-grey for disabled things and key lines. 

![culled and tweaked](https://user-images.githubusercontent.com/29209303/37308407-8efc846e-2603-11e8-8423-1ea2b8acad1a.png)

Then I mapped all of the old colours to the new colours in the `.scss` file for @middle8media to experiment with.

This change is not a departure from our current visual design. I tightened up the palette we already had in the hope that it'll make our UI crisper and less muddy-feeling. As a result, the proposed palette is very minimal. 

## Future

This work needs to be critiqued by @Erioldoesdesign. I will share the results with the rest of the team as well. 

Seth and I will play around a bit and update the issue with changes.

**Comment by middle8media** [comment]
@justinscherer this is great!! Thank you. I will jump into this once @Erioldoesdesign reviews.

**Comment by Erioldoesdesign** [comment]
Love this and I have but one critique! 

We may end up needing lighter versions of red/green. Though they will likely not pass contrast 4:5. I don't think this stops this work from being started but I'm anticipating this possible cropping up.

We also may want to see if a non-brand yellow or orange is worth looking into so we have the 'traffic light' colours red/orange/green

**Comment by middle8media** [comment]
The new color palette is in [this commit](https://github.com/ushahidi/platform-pattern-library/commit/4230c003b959531f57e79ede20b280269c20bcc2) in the [accessibility branch](https://github.com/ushahidi/platform-pattern-library/tree/accessibility). @justinscherer and @Erioldoesdesign, would you be able to pull down the branch, test the colors in all pages/layouts, and make notes of anything that needs to be adjusted? We should be able to merge this very soon, then I will continue working on other accessibility stuff. Thanks.

**Comment by justinscherer** [comment]
The main things that are broken seem to be the backgrounds behind cards should be the `$bg-grey: #F1F1F4` instead of white and we need to refactor the red error styles so that they don't require contrasting reds. The links in the settings menu are a tiny bit janky, but I put some changes in #190 which should help out.

**Comment by Erioldoesdesign** [comment]
The hover colour for the link blue passes contrast ratio but doesn't really look much different to the active or visited state. The underline changes from dotted to solid though so still some indication of state change.
Not particularly a usability issue more of a 'Have I clicked this before? Am I hovering over this?' kind of user question

Found a random turqoiuse: 
![screen shot 2018-03-19 at 14 02 09](https://user-images.githubusercontent.com/11681324/37600092-381809a4-2b7e-11e8-88b3-fa4f06ae6855.png)
![screen shot 2018-03-19 at 14 02 18](https://user-images.githubusercontent.com/11681324/37600097-39a4244c-2b7e-11e8-825f-132a4ab3fc9c.png)

I think there's a few bugs to raise off the back of these changes that re best kept in seperate tickets. Like the above ^^ and maybe this not being able to be read at that grey (so we need to change to white etc.):
![screen shot 2018-03-19 at 14 04 35](https://user-images.githubusercontent.com/11681324/37600172-7902aa50-2b7e-11e8-930f-9c07965d3a33.png)

**Comment by justinscherer** [comment]
We can continue to address this in the individual tickets Eriol opened.

**Comment by justinscherer** [comment]
potential pretty purple to add to the list as an accent colour.looks nice on white with the rest of our colour and is a complimentary (triadic) colour with our blue-grey

#2618B1

**Comment by sethburtonhall** [comment]
> potential pretty purple (#2618B1) to add to the list as an accent colour.

added this as accent color
