### ISSUE TITLE
Post "pins" are difficult to see

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform-pattern-library#37]
The large white center against the white on the map makes it hard to see the pins. Consider restyling, playing with the inside border, changing the white to off white, reducing white size, or changing back shadow or size of pins. Also the pin has a squared top, which is strange.
<img width="89" alt="screen shot 2016-05-05 at 6 06 22 pm" src="https://cloud.githubusercontent.com/assets/1618793/15061618/5229a264-12ec-11e6-8e8f-e60b02c8fb34.png">

**Comment by brandonrosage** [comment]
I've fixed the hard edge at the top. But let's get into the rest...

First, it's important to consider that we don't get to pick the color of the markers. It's the No. 1 challenge here. In many cases, there will be multiple colors, in order to call out the survey they belong to. So anything we do to them has to be color-neutral -- black, white, or somewhere in between.

Second, the zoom level of the map has an enormous impact on visual contrast. The greater the zoom level, the more detail there is to compete with the markers. And as an extension of this, the base layer (which our users can change) impacts this tremendously, as well.

Third, I've carefully reviewed other services' visual treatment of markers. They choose the marker color and base layer, of course. And in many cases, the contrast they apply to the marker has less impact than the Mustang marker.

Bing:

![image](https://cloud.githubusercontent.com/assets/1136279/15078751/58c459e6-137a-11e6-9a70-8be804f97558.png)

Google: 

![image](https://cloud.githubusercontent.com/assets/1136279/15078775/79a5edaa-137a-11e6-82e6-d4a91beae5eb.png)

OpenStreetMap (Humanitarian):

![image](https://cloud.githubusercontent.com/assets/1136279/15078843/db4c8c4e-137a-11e6-93ee-0257d487d1b2.png)

Mustang:

![image](https://cloud.githubusercontent.com/assets/1136279/15079074/042e70f4-137c-11e6-9306-09c63112bd17.png)

I think it's the gold marker that's most problematic in the demo because it happens to be on top of lower-contrast colors. So I've revised the marker treatment to use a much darker shadow to improve the contrast between the marker and what's immediately around it.

The white center, however, is doing some pretty heavy lifting in the contrast department. One it goes greyer, it blends in with the base layer. Once it goes black, it knows out the marker color. 

So I think we have a pretty reasonable solution that's competitive with the other services' experience.

**Comment by caharding** [comment]
I still am having trouble reading the markers at different zoom levels. The
colors we've chosen against this basemap just seem to blend in for me,
where the other maps all seem more readable. Though colors and base layers
are surely changeable, I think the default should be hyper legible. If you
disagree I would at least suggest asking this in user tests and potentially
showing them other maps to see what people prefer.

On Friday, May 6, 2016, Brandon Rosage <notifications@github.com> wrote:

> I've fixed the hard edge at the top. But let's get into the rest...
>
> First, it's important to consider that we don't get to pick the color of
> the markers. It's the No. 1 challenge here. In many cases, there will be
> multiple colors, in order to call out the survey they belong to. So
> anything we do to them has to be color-neutral -- black, white, or
> somewhere in between.
>
> Second, the zoom level of the map has an enormous impact on visual
> contrast. The greater the zoom level, the more detail there is to compete
> with the markers. And as an extension of this, the base layer (which our
> users can change) impacts this tremendously, as well.
>
> Third, I've carefully reviewed other services' visual treatment of
> markers. They choose the marker color and base layer, of course. And in
> many cases, the contrast they apply to the marker has less impact than the
> Mustang marker.
>
> Bing:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1136279/15078751/58c459e6-137a-11e6-9a70-8be804f97558.png>
>
> Google:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1136279/15078775/79a5edaa-137a-11e6-82e6-d4a91beae5eb.png>
>
> OpenStreetMap (Humanitarian):
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1136279/15078843/db4c8c4e-137a-11e6-93ee-0257d487d1b2.png>
>
> Mustang:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1136279/15079074/042e70f4-137c-11e6-9306-09c63112bd17.png>
>
> I think it's the gold marker that's most problematic in the demo because
> it happens to be on top of lower-contrast colors. So I've revised the
> marker treatment to use a much darker shadow to improve the contrast
> between the marker and what's immediately around it.
>
> The white center, however, is doing some pretty heavy lifting in the
> contrast department. One it goes greyer, it blends in with the base layer.
> Once it goes black, it knows out the marker color.
>
> So I think we have a pretty reasonable solution that's competitive with
> the other services' experience.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ushahidi/platform-pattern-library/issues/37#issuecomment-217488805>
>


-- 
Charlie Harding
Product Director

**Comment by brandonrosage** [comment]
I've revised the structure of map markers to allow us to do a treatment like this:

![image](https://cloud.githubusercontent.com/assets/1136279/15118132/806015d2-15d0-11e6-9f8a-684eda5c985d.png)
