### ISSUE TITLE
Where should message thread appear in the Mustang UI?

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform-pattern-library#64]
Previously we have a view of  a posts associated messages. This doesn't appear in the mustang layouts. Is it now part of the post detail? or non existent?

**Comment by brandonrosage** [comment]
I intended to suggest (but never communicated) that the same listing pattern we use for "Comments" would be used for "Messages." It's now included on the layout: https://github.com/ushahidi/platform-pattern-library/blob/mustang/pattern-library/5_layouts/post-detail.html#L251-L301

If there's some functionality that I haven't accounted for, please let me know and I'll design for it.

**Comment by rjmackay** [comment]
Ah. Actually I think we talked about that months ago.. sorry for not keeping track.

- We're missing some way to show if messages are incoming or outgoing
  - This might also double as highlighting Administrator replies to comments
- Is there anywhere I could show whats being listed ie "Messages exchanged with 012 123456"
- Minor: Add message should probably be 'reply'

**Comment by brandonrosage** [comment]
[I've revised this pattern a bit](https://github.com/ushahidi/platform-pattern-library/blob/mustang/pattern-library/5_layouts/post-detail.html#L251-L300) to include the content you mentioned. Some of it (namely the matter of "incoming" and "outgoing") I'm not 100 percent clear on. So there's a modest attempt to address it.

![Screenshot of Conversation](https://cloud.githubusercontent.com/assets/1136279/15756279/2b045748-28c6-11e6-9c8d-138ee5b49090.png)

The big changes are:

- Renaming the title "Conversation with author," since, as I understand it, that's effectively what it is. It's not  a launching point for sending messages to anyone.
- Removing the avatar from the author, since they're likely identified by an arbitrary SMS number and, at best, a name.
- Allowing for an appended icon in the structure for the user image. In this case, there's a "reply" arrow appended to your reply.
- Relabeling the "Add message" button to "Send new message." This accounts for the possibility that you (or another deployment operator) has sent the author a message that has gone unanswered. If the button always read "reply," it might imply you're replying to your own message. So I think it'd be wise to label it as something to sends along a new message into the thread.

**Comment by rjmackay** [comment]
Great. That looks excellent.

**Comment by rjmackay** [comment]
@jasonmule I think you were working on implementing this?
