### ISSUE TITLE
Large blank space at the bottom of modals

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform-pattern-library#85]
<img width="536" alt="screenshot 2016-10-05 12 45 42" src="https://cloud.githubusercontent.com/assets/7965/19096543/b89dc9fa-8af9-11e6-8694-cd93a5c6b400.png">

In most cases this is added so that modal content can be scrolled above the `modal-actions` div, but when there is no modal-actions div the padding is still present.

**Comment by brandonrosage** [comment]
`.modal-body` and `.modal-actions` are intended to work in concert. So if you have a modal window with no actions, just refrain from wrapping the "body" in the `.modal-body` container -- simply don't use that wrapper.

## _Aside_

[The upcoming "free-form surveys" solution](https://github.com/ushahidi/platform/issues/1335#issuecomment-250867949) reinforces the use of the "mainsheet" pattern, which is particularly useful for interactions like "Add field," where there's a single-click interaction -- not configure-and-confirm.

In practice, "Add field" then looks like this on small-screen:

![small screen](https://cloud.githubusercontent.com/assets/1136279/19117874/2dacf4ba-8ae0-11e6-945d-e421f58c160a.png)

...and like this on large-screen:

![large screen](https://cloud.githubusercontent.com/assets/1136279/19008562/cac3f3c8-8731-11e6-9fd4-9f30de36649c.png)

**Comment by rjmackay** [comment]
> .modal-body and .modal-actions are intended to work in concert. So if you have a modal window with no actions, just refrain from wrapping the "body" in the .modal-body container -- simply don't use that wrapper.

Ok. In principle that makes sense. However the dynamic height of modals relies on having a `modal-body` div. The PL uses the modal-body container, and we do the same in client.

**Comment by brandonrosage** [comment]
If conditional use of the `.modal-body` wrapper isn't possible, I'd lobby for supporting the `.mainsheet` pattern in the client, since it exists primarily to serve as an interstitial window with **no** window-level actions (like Save or Cancel). 

I've ensured the `develop` branch has the HTML, CSS, and JS necessary to support it. 

If you'd like, @rjmackay, I can create an issue dedicated to the task of implementing support in the client. On the other hand, I can see _this_ issue essentially serving that purpose -- that fixing the issue you've raised is accomplished by building support for `mainsheet`.

**Comment by rjmackay** [comment]
@middle8media if you could flag where we need to replace modals with mainsheet patterns, I can update in the client. *or* given @ryanchristo already built the pattern maybe you could just swap the functions on the client
