### ISSUE TITLE
Settings button isn't visible in menu on small screens

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform-pattern-library#86]
Expected:
- When I click 'More' on a small screen I can see settings menu item

Actual:
- No way to get to settings on a small screen

**Comment by rjmackay** [comment]
I'm also not at all clear **why** we changed the approach to the mode-bar. the `tuck` and `persist` classes worked well. This change (568c8589) doesn't seem any cleaner than previous, and also relies on some fragile styling/markup using `.active + ul`

**Comment by rjmackay** [comment]
Related: It seems like the 'active' highlight on settings isn't working correctly. Not sure if thats my change, or something else. But needs a fix

**Comment by brandonrosage** [comment]
I've staged a fix for this in a feature branch: [`f-modebar`](https://github.com/ushahidi/platform-pattern-library/tree/f-modebar). It's a very modest HTML structural revision, coupled with some CSS tweaks. It'd be pretty trivial to implement in an upcoming sprint, I think.

In fact, "Settings" has been (and is) available on small screens. But some of the limitations of the structure of the Mode Bar meant it had to be displayed at the bottom of the screen, rather than in the list at the top. 👎 

This is fixed.

**Comment by jshorland** [comment]
to do: @jshorland double check this.

**Comment by middle8media** [comment]
@jess where are we on this? Can brandon's fix be merged?

**Comment by jshorland** [comment]
@middle8media i'd love to merge brandon's fix if possible. @rjmackay ?

**Comment by rjmackay** [comment]
I'll look at merging in the PL - its in a slightly weird state. Then we can test that out on staging.
